-- 001_init.sql — the ontology's physical schema.
--
-- Five tables: three are the ontology (objects, object_properties, links) and two are
-- governance (audit_records, schema_versions). See PLAN.md §5.
--
-- No schema_versions row is inserted here. Its object_types/link_types payload comes
-- from the definitions in @sourcing/ontology, which do not exist yet, so the row lands
-- in 002 where the payload and the code that produces it are reviewed together. Until
-- then objects.schema_version has nothing to reference and no object can be inserted,
-- which is the intended gate rather than an oversight.


-- ---------------------------------------------------------------------------
-- Domains
--
-- confidence and method appear identically on object_properties and links. Defining
-- them once means the confidence range rule has exactly one owner.
-- ---------------------------------------------------------------------------

-- numeric, not float: the verified-implies-1.0 constraints below compare for exact
-- equality, and 1.0 is not reliably representable in binary floating point.
CREATE DOMAIN confidence_score AS numeric(4, 3)
    CHECK (VALUE >= 0 AND VALUE <= 1);

CREATE DOMAIN provenance_method AS text
    CHECK (VALUE IN ('DIRECT', 'FUZZY_MATCH', 'LLM_EXTRACTION', 'HUMAN_ENTRY', 'INFERRED'));


-- ---------------------------------------------------------------------------
-- schema_versions — the schema is versioned data, not only code (ONTOLOGY.md §6)
-- ---------------------------------------------------------------------------

CREATE TABLE schema_versions (
    version         text        NOT NULL,
    object_types    jsonb       NOT NULL,
    link_types      jsonb       NOT NULL,
    applied_at      timestamptz NOT NULL DEFAULT now(),
    applied_via     text        NOT NULL,

    -- The foreign key is added after audit_records exists: the two tables reference
    -- each other. The cycle is satisfiable because this side is nullable.
    audit_record_id uuid,

    CONSTRAINT schema_versions_pkey PRIMARY KEY (version),

    CONSTRAINT schema_versions_applied_via_known
        CHECK (applied_via IN ('MIGRATION', 'AGENT_PROPOSAL')),

    CONSTRAINT schema_versions_object_types_is_array
        CHECK (jsonb_typeof(object_types) = 'array'),

    CONSTRAINT schema_versions_link_types_is_array
        CHECK (jsonb_typeof(link_types) = 'array'),

    -- A schema change an agent proposed must point at the record that authorised it.
    -- Agents may propose; they may never be the sole reason the schema moved.
    CONSTRAINT schema_versions_agent_change_is_audited
        CHECK (applied_via = 'MIGRATION' OR audit_record_id IS NOT NULL)
);


-- ---------------------------------------------------------------------------
-- audit_records — every mutation writes one, append-only (ONTOLOGY.md §5)
-- ---------------------------------------------------------------------------

CREATE TABLE audit_records (
    -- uuid rather than text, unlike objects.id below: audit record IDs are generated by
    -- the system and never authored by a human or typed into a URL.
    id             uuid        NOT NULL DEFAULT gen_random_uuid(),

    action_name    text        NOT NULL,
    actor          text        NOT NULL,
    actor_type     text        NOT NULL,
    proposed_at    timestamptz NOT NULL DEFAULT now(),
    approved_by    text,
    approved_at    timestamptz,
    status         text        NOT NULL,
    justification  text        NOT NULL,
    input_payload  jsonb       NOT NULL,

    -- Nullable because a PROPOSED or REJECTED action never produced an after state.
    before_state   jsonb,
    after_state    jsonb,

    schema_version text        NOT NULL
                               REFERENCES schema_versions (version) ON DELETE RESTRICT,

    CONSTRAINT audit_records_pkey PRIMARY KEY (id),

    CONSTRAINT audit_records_actor_type_known
        CHECK (actor_type IN ('HUMAN', 'AGENT')),

    CONSTRAINT audit_records_status_known
        CHECK (status IN ('PROPOSED', 'APPROVED', 'REJECTED', 'EXECUTED')),

    -- Set together or not at all, so an approval always has a timestamp.
    CONSTRAINT audit_records_approved_pair
        CHECK ((approved_by IS NULL) = (approved_at IS NULL)),

    -- An approver on a PROPOSED or REJECTED record is incoherent.
    CONSTRAINT audit_records_approved_status
        CHECK (approved_by IS NULL OR status IN ('APPROVED', 'EXECUTED'))
);

-- Serves the pending-approval queue, which is the read behind the Action
-- propose/approve endpoints.
CREATE INDEX audit_records_status_idx
    ON audit_records (status, proposed_at DESC);

ALTER TABLE schema_versions
    ADD CONSTRAINT schema_versions_audit_record_fkey
    FOREIGN KEY (audit_record_id) REFERENCES audit_records (id) ON DELETE RESTRICT;


-- ---------------------------------------------------------------------------
-- objects — identity only, no properties
--
-- Keeping identity separate from properties is what lets a future merge repoint an
-- object's properties without rewriting its identity.
-- ---------------------------------------------------------------------------

CREATE TABLE objects (
    -- text rather than uuid, unlike audit_records.id and links.id above and below:
    -- object IDs are human-authored, survive merges, appear in API paths and in seed
    -- fixtures, and ONTOLOGY.md types them as string. `SUP-0001` beats a UUID when you
    -- are reading a traversal result by eye. The asymmetry is deliberate: IDs people
    -- write and read are text, IDs only the system ever handles are uuid.
    id             text        NOT NULL,

    object_type    text        NOT NULL,
    schema_version text        NOT NULL
                               REFERENCES schema_versions (version) ON DELETE RESTRICT,
    created_at     timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT objects_pkey PRIMARY KEY (id),

    CONSTRAINT objects_id_not_blank
        CHECK (id <> ''),

    CONSTRAINT objects_object_type_known
        CHECK (object_type IN ('SUPPLIER', 'PART', 'DEVICE', 'SITE', 'QUALITY_EVENT'))
);

CREATE INDEX objects_object_type_idx ON objects (object_type);


-- ---------------------------------------------------------------------------
-- object_properties — the Tracked<T> layer
--
-- Current state, mutated in place. History lives in audit_records with before/after
-- state; making this table append-only as well would create two histories that can
-- disagree.
-- ---------------------------------------------------------------------------

CREATE TABLE object_properties (
    object_id         text              NOT NULL
                                        REFERENCES objects (id) ON DELETE RESTRICT,
    property_name     text              NOT NULL,
    ordinal           integer           NOT NULL DEFAULT 0,

    value             jsonb             NOT NULL,
    value_type        text              NOT NULL,

    confidence        confidence_score  NOT NULL,

    -- Provenance expanded into columns rather than held as one jsonb blob, so lineage
    -- and calibration are plain WHERE clauses: group confidence by method to check
    -- calibration, or find everything one pipeline_run_id touched in order to retract
    -- it.
    source_system     text              NOT NULL,
    source_record_id  text,
    pipeline_run_id   text,
    extracted_at      timestamptz       NOT NULL,
    method            provenance_method NOT NULL,

    verified_by       text,
    verified_at       timestamptz,

    -- Arrays are rows sharing an object_id and property_name, distinguished by ordinal;
    -- scalars are ordinal 0. This key's leading-edge prefix also serves object
    -- assembly, which is why no separate (object_id, property_name) index exists.
    CONSTRAINT object_properties_pkey PRIMARY KEY (object_id, property_name, ordinal),

    CONSTRAINT object_properties_ordinal_non_negative
        CHECK (ordinal >= 0),

    CONSTRAINT object_properties_name_not_blank
        CHECK (property_name <> ''),

    CONSTRAINT object_properties_value_type_known
        CHECK (value_type IN ('STRING', 'NUMBER', 'BOOLEAN', 'TIMESTAMP')),

    -- Recovers the one piece of EAV type safety that is recoverable in the database:
    -- the discriminator is checked against the jsonb it claims to describe, so it
    -- cannot drift into decoration. A disjunction rather than a CASE, because a CASE
    -- with no matching branch yields NULL and a CHECK that evaluates to NULL passes.
    --
    -- TIMESTAMP is checked only as far as "is a string". Format validation belongs to
    -- Zod at the repository boundary; duplicating it here would give it two owners.
    CONSTRAINT object_properties_value_matches_value_type
        CHECK (
               (value_type = 'STRING'    AND jsonb_typeof(value) = 'string')
            OR (value_type = 'NUMBER'    AND jsonb_typeof(value) = 'number')
            OR (value_type = 'BOOLEAN'   AND jsonb_typeof(value) = 'boolean')
            OR (value_type = 'TIMESTAMP' AND jsonb_typeof(value) = 'string')
        ),

    -- An INFERRED value is derived from other tracked values, so it has no raw source
    -- row to point at. A null says that plainly; overloading the column to sometimes
    -- mean "raw source" and sometimes "the properties this was derived from" would give
    -- it two meanings, which is worse. Derivation tracking gets its own structure when
    -- INFERRED values actually arrive.
    CONSTRAINT object_properties_source_record_unless_inferred
        CHECK (source_record_id IS NOT NULL OR method = 'INFERRED'),

    -- A human-entered value has no ingestion run to attribute it to. Synthesising one
    -- would corrupt the "everything pipeline run X touched" retraction query.
    CONSTRAINT object_properties_pipeline_run_unless_human
        CHECK (pipeline_run_id IS NOT NULL OR method = 'HUMAN_ENTRY'),

    -- Human verification means certainty. A verified property cannot stay probabilistic.
    CONSTRAINT object_properties_verified_implies_certain
        CHECK (verified_by IS NULL OR confidence = 1.0),

    -- Set together or not at all, so audit reconstruction always has a timestamp.
    CONSTRAINT object_properties_verified_pair
        CHECK ((verified_by IS NULL) = (verified_at IS NULL))
);

-- The low-confidence review queue. Partial, so the index stays proportional to the work
-- outstanding rather than to the table: verified rows are all 1.0 and never queue.
CREATE INDEX object_properties_review_queue_idx
    ON object_properties (confidence)
    WHERE verified_by IS NULL;


-- ---------------------------------------------------------------------------
-- links — typed, directional relationships carrying their own confidence
-- ---------------------------------------------------------------------------

CREATE TABLE links (
    -- uuid, like audit_records.id: nobody authors a link ID by hand.
    id                uuid              NOT NULL DEFAULT gen_random_uuid(),

    link_type         text              NOT NULL,
    from_id           text              NOT NULL
                                        REFERENCES objects (id) ON DELETE RESTRICT,
    to_id             text              NOT NULL
                                        REFERENCES objects (id) ON DELETE RESTRICT,

    -- A column here rather than a row in object_properties: weakest-link traversal must
    -- accumulate LEAST(...) while walking edges, without a join per hop. This is the
    -- one place the uniform EAV treatment is deliberately not applied.
    confidence        confidence_score  NOT NULL,

    source_system     text              NOT NULL,
    source_record_id  text,
    pipeline_run_id   text,
    extracted_at      timestamptz       NOT NULL,
    method            provenance_method NOT NULL,

    verified_by       text,
    verified_at       timestamptz,

    created_at        timestamptz       NOT NULL DEFAULT now(),

    CONSTRAINT links_pkey PRIMARY KEY (id),

    CONSTRAINT links_unique_edge UNIQUE (link_type, from_id, to_id),

    CONSTRAINT links_link_type_known
        CHECK (link_type IN ('SUPPLIES', 'COMPOSED_OF', 'MANUFACTURED_AT',
                             'AFFECTS_SUPPLIER', 'AFFECTS_PART')),

    -- All five Week 1 link types join different object types, so a self-edge is always
    -- malformed, and it is the cheapest degenerate cycle to exclude up front.
    CONSTRAINT links_no_self_reference
        CHECK (from_id <> to_id),

    CONSTRAINT links_source_record_unless_inferred
        CHECK (source_record_id IS NOT NULL OR method = 'INFERRED'),

    CONSTRAINT links_pipeline_run_unless_human
        CHECK (pipeline_run_id IS NOT NULL OR method = 'HUMAN_ENTRY'),

    CONSTRAINT links_verified_implies_certain
        CHECK (verified_by IS NULL OR confidence = 1.0),

    CONSTRAINT links_verified_pair
        CHECK ((verified_by IS NULL) = (verified_at IS NULL))
);

-- Traversal reads edges in both directions. The critical path is
--   Supplier --SUPPLIES--> Part <--COMPOSED_OF-- Device --MANUFACTURED_AT--> Site
-- where the second hop runs against the arrow. links_unique_edge leads with link_type
-- and so serves neither direction.
CREATE INDEX links_from_idx ON links (from_id, link_type);
CREATE INDEX links_to_idx   ON links (to_id, link_type);

-- The mirror of object_properties_review_queue_idx. Path confidence is the minimum
-- along the path and link confidence is usually what sets that minimum, so a review
-- queue blind to links would systematically hide the weakest evidence in the graph.
CREATE INDEX links_review_queue_idx
    ON links (confidence)
    WHERE verified_by IS NULL;
